### ISSUE TITLE
Include more information with UnknownError

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [expo-community/expo-server-sdk-ruby#33]
I recently got a bunch of `An unknown error occurred. (Exponent::Push::UnknownError)` errors:

```
/app/codecademy/shared/bundle/ruby/2.5.0/gems/exponent-server-sdk-0.0.6/lib/exponent-server-sdk.rb:57:in `handle': An unknown error occurred. (Exponent::Push::UnknownError)
  from /app/codecademy/shared/bundle/ruby/2.5.0/gems/exponent-server-sdk-0.0.6/lib/exponent-server-sdk.rb:20:in `publish'
  from script/mobile/send_reminder_notifications.rb:18:in `block in send_notifications'
  ...(more from our call stack)
```

...that's about all the info contained. Is it possible to have more debug info logged with `UnknownError`? Maybe some or all of: the request URI, server response code, any error text it includes, some kind of unique ID if that exists in the system?

**Comment by Aryk** [comment]
I think some recent updates broke this thing... I'm getting:

Exponent::Push::UnknownError: Unknown error format: #<Typhoeus::Response:0x00007fbcf7cf03f8>

When I inspect the object, I can find the issues buried deep inside.

**Comment by jpbaeza** [comment]
Same problem here

**Comment by foolem** [comment]
I'm facing this issue too, a lot of notifications are raising this error, and I don''t know what's happening

**Comment by JoshuaKGoldberg** [comment]
Closing out my old issues for repos I no longer have context on. If anybody has a need for what this issue was asking about, I'd encourage them/you to file a new issue. Cheers!
